name: login
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  geolocator: ^13.0.1
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env # .envの設定を追加.

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon_kenryo.png"